export const WISHLIST_FETCH_REQUEST = "WISHLIST_FETCH_REQUEST";
export const WISHLIST_FETCH_SUCCESS = "WISHLIST_FETCH_SUCCESS";
export const WISHLIST_FETCH_FAIL    = "WISHLIST_FETCH_FAIL";

export const WISHLIST_ADD_REQUEST   = "WISHLIST_ADD_REQUEST";
export const WISHLIST_ADD_SUCCESS   = "WISHLIST_ADD_SUCCESS";
export const WISHLIST_ADD_FAIL      = "WISHLIST_ADD_FAIL";

export const WISHLIST_REMOVE_REQUEST = "WISHLIST_REMOVE_REQUEST";
export const WISHLIST_REMOVE_SUCCESS = "WISHLIST_REMOVE_SUCCESS";
export const WISHLIST_REMOVE_FAIL    = "WISHLIST_REMOVE_FAIL";

export const WISHLIST_RESET = "WISHLIST_RESET";
